# Generated by Django 4.1.7 on 2023-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('PropertyId', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Operation', models.CharField(max_length=50)),
                ('Details', models.TextField(max_length=500)),
                ('Image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
