# Generated by Django 4.1.7 on 2023-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0002_property_dimension_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Interest',
            field=models.CharField(default='houses', max_length=200),
            preserve_default=False,
        ),
    ]
