# Generated by Django 4.1.7 on 2023-04-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0003_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(default='client', max_length=50),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('VisitId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Hour', models.TimeField(auto_now_add=True)),
                ('PropertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.property')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.user')),
            ],
        ),
    ]
