# Generated by Django 4.1.7 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0004_alter_user_role_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='Hour',
        ),
        migrations.AlterField(
            model_name='visit',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
