# Generated by Django 4.1.7 on 2023-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0005_remove_visit_hour_alter_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='Hour',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
