# Generated by Django 4.1.7 on 2023-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0006_visit_hour_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='Date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
